name: Build and deploy ASP.Net Core API to Azure Web App - MsaReactJsBackend

on:
  push:
    branches:
      - master  # or your main branch
 
jobs:
  build-and-deploy-backend:
    runs-on: windows-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore dependencies
        run: dotnet restore StudendtMSAReact/StudendtMSAReact/StudendtMSAReact.csproj


      - name: Build backend
        run: dotnet build StudendtMSAReact/StudendtMSAReact/StudendtMSAReact.csproj --configuration Release --no-restore

      - name: Publish backend project
        run: dotnet publish StudendtMSAReact/StudendtMSAReact/StudendtMSAReact.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: MsaReactJsCollege  # Your Azure App Service name
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: ./publish
